// Code generated by Kitex v0.5.1. DO NOT EDIT.
package videorpc

import (
	server "github.com/cloudwego/kitex/server"
	video "tiktok_micro/kitex_gen/video"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler video.VideoRpc, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
